services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_VERTEX_API_URL: http://localhost:3020
    restart: unless-stopped
    environment:
      VERTEX_API_URL: http://localhost:3020
    ports:
      - '3021:3021'
